#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

// note boards.py sets this, so the default value in here doesn't
// really matter:
//#ifndef AP_CUSTOMCONTROL_ENABLED
//#define AP_CUSTOMCONTROL_ENABLED 0
//#endif

#ifndef AP_CUSTOMCONTROLPLANE_BACKEND_DEFAULT_ENABLED
#define AP_CUSTOMCONTROLPLANE_BACKEND_DEFAULT_ENABLED AP_CUSTOMCONTROLPLANE_ENABLED
#endif

#ifndef AP_CUSTOMCONTROLPLANE_EMPTY_ENABLED
#define AP_CUSTOMCONTROLPLANE_EMPTY_ENABLED AP_CUSTOMCONTROLPLANE_BACKEND_DEFAULT_ENABLED
#endif

#ifndef AP_CUSTOMCONTROLPLANE_PID_ENABLED
#define AP_CUSTOMCONTROLPLANE_PID_ENABLED AP_CUSTOMCONTROLPLANE_BACKEND_DEFAULT_ENABLED
#endif

#ifndef AP_CUSTOMCONTROLPLANE_XYZ_ENABLED
#define AP_CUSTOMCONTROLPLANE_XYZ_ENABLED AP_CUSTOMCONTROLPLANE_BACKEND_DEFAULT_ENABLED
#endif